name: Stonefish ROS 2 Build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # Runs daily at 01:00 UTC
jobs:
  call_reusable_workflow:
    strategy:
      matrix:
        test_script:
          - "scripts/build-package.sh"
    uses: vortexntnu/vortex-ci/.github/workflows/reusable-ros2-simulator-test.yml@main
    with:
      setup_script: "scripts/stonefish-setup.sh"
      test_script: "${{ matrix.test_script }}"